# Generated by Django 5.2.4 on 2025-08-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='genre',
            field=models.CharField(choices=[('classic_rock', 'Classic Rock'), ('rock', 'Rock'), ('hard_rock', 'Hard Rock'), ('metal', 'Metal'), ('heavy_metal', 'Heavy Metal')], default='rock', max_length=20),
        ),
    ]
