# Generated by Django 5.2.4 on 2025-08-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_event_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age',
            field=models.CharField(blank=True, choices=[('All Ages', 'All Ages'), ('18+', '18+ only'), ('14+', '14+ must be accompanied by an adult')], max_length=35, null=True),
        ),
    ]
