# Generated by Django 5.2.4 on 2025-08-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_event_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age',
            field=models.CharField(choices=[('All Ages', 'All Ages'), ('18+', '18+ only'), ('14+', '14+ must be accompanied by an adult')], default='14+ must be accompanied by an adult', max_length=100),
        ),
    ]
