# Generated by Django 5.2.4 on 2025-08-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_event_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='supporting_artists',
            field=models.ManyToManyField(blank=True, help_text='Select supporting artists from the dropdown', related_name='supporting_for', to='products.artist'),
        ),
    ]
