# Generated by Django 5.2.4 on 2025-08-25 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_event_supporting_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
