# Generated by Django 5.2.4 on 2025-08-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Optional: Add a title for the event (e.g. Tour Name)', max_length=200, null=True),
        ),
    ]
