# Generated by Django 5.2.4 on 2025-08-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='special_event',
            field=models.BooleanField(default=False),
        ),
    ]
