# Generated by Django 5.2.4 on 2025-08-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_event_special_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='festival_day',
            field=models.CharField(blank=True, choices=[('day1', 'Day 1'), ('day2', 'Day 2')], max_length=10, null=True),
        ),
    ]
