# Generated by Django 5.2.4 on 2025-08-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_event_festival_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='festival_day',
            field=models.CharField(blank=True, choices=[('day1', 'Day 1'), ('day2', 'Day 2'), ('roxoff', 'Roxoff')], max_length=10, null=True),
        ),
    ]
