# Generated by Django 5.2.4 on 2025-08-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_event_festival_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='festival_day',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('regular', 'Regular Event'), ('roxoff', 'Roxoff')], default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='roxoff_day',
            field=models.CharField(blank=True, choices=[('day1', 'Day 1'), ('day2', 'Day 2')], help_text='Only required for Roxoff events', max_length=10, null=True),
        ),
    ]
