# Generated by Django 5.2.4 on 2025-08-31 17:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_event_festival_day_event_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=120)),
                ('product_description', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_category', models.CharField(choices=[('tshirt', 'T-Shirt'), ('hoodie', 'Hoodie'), ('flag', 'Flag'), ('cap', 'Cap'), ('mug', 'Mug'), ('other', 'Other')], max_length=20)),
                ('size', models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], help_text='Leave blank for items without sizes (flags, mugs, etc.).', max_length=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Units per product item (keep 1 unless you sell multi-packs).')),
                ('stock', models.PositiveIntegerField(default=0, help_text='How many you have in stock.')),
            ],
        ),
    ]
