# Generated by Django 5.2.4 on 2025-09-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_merch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='product_id',
        ),
    ]
