# Generated by Django 5.2.4 on 2025-09-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_merch_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merch',
            options={'ordering': ['product_name']},
        ),
        migrations.AlterField(
            model_name='merch',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='merch',
            name='product_category',
            field=models.CharField(choices=[('tshirt', 'T-Shirt'), ('hoodie', 'Hoodie'), ('flag', 'Flag'), ('cap', 'Cap'), ('mug', 'Mug')], max_length=20),
        ),
        migrations.AlterField(
            model_name='merch',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='merch',
            name='size',
            field=models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], help_text='Leave blank for items without sizes (flags, mugs, etc.).', max_length=5, null=True),
        ),
    ]
