# Generated by Django 5.2.4 on 2025-09-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_event_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=6),
        ),
    ]
