# Generated by Django 5.2.4 on 2025-09-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_merch_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
