# Generated by Django 5.2.4 on 2025-09-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_event_ticket_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
