# Generated by Django 5.2.4 on 2025-10-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_venue_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='items_sold',
            field=models.PositiveIntegerField(default=0, help_text='How many units of this item have been sold (auto-updated).'),
        ),
    ]
