# Generated by Django 5.2.4 on 2025-10-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_merch_items_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_sold',
            field=models.PositiveIntegerField(default=0, help_text='How many tickets have been sold (auto-updated).'),
        ),
    ]
