# Generated by Django 5.2.4 on 2025-10-19 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_event_tickets_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=5, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('items_sold', models.PositiveIntegerField(default=0)),
                ('merch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.merch')),
            ],
            options={
                'ordering': ['size'],
            },
        ),
    ]
