# Generated by Django 5.2.4 on 2025-10-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='PENDING', help_text='Latest payment state from Square (e.g. APPROVED, COMPLETED)', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_on',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment status was last verified with Square', null=True),
        ),
    ]
