# Generated by Django 5.2.4 on 2025-10-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_payment_status_order_verified_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='event', max_length=20),
        ),
    ]
