# Generated by Django 5.2.4 on 2025-10-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderitem_event_orderitem_merch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='square_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='square_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
