# Generated by Django 5.2.4 on 2025-10-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orderitem_square_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='square_order_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='square_payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='square_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='square_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
