# Generated by Django 5.2.4 on 2025-10-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
