# Generated by Django 5.2.4 on 2025-10-14 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0006_delete_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_same_address', models.BooleanField(default=True, help_text="Check if invoice uses the same address as the order's shipping details")),
                ('invoice_name', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_company', models.CharField(blank=True, max_length=150, null=True)),
                ('invoice_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('invoice_address', models.TextField(blank=True, null=True)),
                ('invoice_city', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_country', models.CharField(blank=True, default='UK', help_text='Defaults to UK if not specified', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(help_text='The order this invoice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='checkout.order')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
