# Generated by Django 5.2.4 on 2025-09-12 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
        ('products', '0021_alter_merch_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='merch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merch_basket_items', to='products.merch'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_basket_items', to='products.event'),
        ),
    ]
