# Generated by Django 5.2.4 on 2025-09-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_basketitem_merch_alter_basketitem_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='basketitem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
