# Generated by Django 5.2.4 on 2025-09-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_alter_basketitem_options_basketitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=10, null=True),
        ),
    ]
