# Generated by Django 5.2.4 on 2025-09-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_alter_basketitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
